repos:
-   repo: meta
    hooks:
    -   id: identity

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: detect-private-key

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff
    - id: ruff-format

- repo: https://github.com/python-poetry/poetry
  rev: 1.6.1
  hooks:
  -   id: poetry-check
      name: Check that Poetry is all set
  -   id: poetry-lock
      name: Make sure lock file is up to date
      args: [--no-update]

- repo: https://github.com/econchick/interrogate
  rev: 1.5.0
  hooks:
  -   id: interrogate
      args: [-v, --fail-under=100, --ignore-init-module, --ignore-property-decorators, --exclude=tests]
      pass_filenames: false
