python_logs:
  managed_python_loggers:
    - mds_logger
  python_log_level: INFO

telemetry:
  enabled: false

code_servers:
  local_startup_timeout: 600

run_monitoring:
  enabled: true
  start_timeout_seconds: 600
