# Install Python version - from devcontainer.json
ARG PY_VERSION=3.11-bookworm
FROM mcr.microsoft.com/devcontainers/python:1-${PY_VERSION}

# Environment Variables
ENV \
  # Poetry's configuration
  POETRY_NO_INTERACTION=1 \
  POETRY_VIRTUALENVS_CREATE=false \
  POETRY_CACHE_DIR='/var/cache/pypoetry' \
  POETRY_HOME='/usr/local'

# Install Poetry
SHELL ["/bin/bash", "-o", "pipefail", "-c"]
RUN curl -sSL https://install.python-poetry.org | python3 -

# Copy only requirements to cache them
WORKDIR /poetry_install/

# Copy these files into the env_install folder
COPY poetry.lock pyproject.toml /poetry_install/

# Install the environment here
WORKDIR /poetry_install/
RUN poetry install && rm -rf $POETRY_CACHE_DIR
