name: CI Pipeline

on:
    pull_request:
      branches:
        - main
    workflow_dispatch:
      inputs:
        logLevel:
          description: 'Log level'
          required: true
          default: 'warning'
          type: choice
          options:
          - info
          - warning
          - debug
        tags:
          description: 'Test scenario tags'
          required: false
          type: boolean

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          pull-requests: write
          contents: read
        timeout-minutes: 8
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v3
              with:
                persist-credentials: false
                fetch-depth: 0

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.10'
                cache: 'pip'

            - name: Install poetry
              uses: snok/install-poetry@v1

            - name: Install library
              run: poetry install

            - name: Run Pre-commit Hooks
              uses: pre-commit/action@v3.0.0

            - name: Test with pytest
              run: |
                pytest --junitxml=junit/test-results.xml --cov --cov-report xml

            - name: Pytest coverage comment
              id: coverageComment
              uses: MishaKav/pytest-coverage-comment@v1.1.48
              with:
                  pytest-xml-coverage-path: ./coverage.xml
                  junitxml-path: junit/test-results.xml
